pipeline {
    agent any
    def dockerImage
    def version = "1.0"
    def mvnHome = tool 'maven-3.6.3'
    stage('Prepare') {
        git url: 'https://github.com/mohancse1707/springboot-microservice-application.git'
    }
    stage('Build') {
        sh "'${mvnHome}/bin/mvn' -f springboot-microservice-application/product-micro-service clean install"
    }

    stage('Docker Image') {
        dockerImage = docker.build("product-micro-service:${version}")
    }

    stage('Docker Deploy') {
        sh "docker stop product-micro-service:${version}"
        sh "docker rm product-micro-service:${version}"
        sh "docker run -d -p 8083:8083 product-micro-service:${version}"
    }
}
